### ISSUE TITLE
jspm install -y fails

### ISSUE THREAD

**Issue by col-panic** [phwiget/ebox-elexis#2]
Marcos-MBP:frontend marco$ jspm install -y

```
err  TypeError: Install of aurelia-http-client to 1.0.2 has no registry property provided.
         at /Users/marco/git/ebox-elexis/frontend/node_modules/jspm/lib/package.js:314:13
         at Array.forEach (native)
         at processDeps (/Users/marco/git/ebox-elexis/frontend/node_modules/jspm/lib/package.js:297:21)
         at setDefaults (/Users/marco/git/ebox-elexis/frontend/node_modules/jspm/lib/config/package.js:129:28)
         at PackageJSON.read (/Users/marco/git/ebox-elexis/frontend/node_modules/jspm/lib/config/package.js:116:3)
         at /Users/marco/git/ebox-elexis/frontend/node_modules/jspm/lib/config.js:80:25
         at process._tickCallback (internal/process/next_tick.js:109:7)
         at Module.runMain (module.js:607:11)
         at run (bootstrap_node.js:427:7)
         at startup (bootstrap_node.js:148:9)
         at bootstrap_node.js:542:3
```

warn Installation changes not saved.

**Comment by phwiget** [comment]
Does it work with this (<https://github.com/phwiget/ebox-elexis/commit/a6db367e3102c552ba4e1360b3108c9e518cc6c3>) commit and `npm install` beforehand?

**Comment by col-panic** [comment]
Sorry, no it doesn't!

**Comment by col-panic** [comment]
The following seems to work

```
       "typeahead.js": "npm:typeahead.js@^0.11.1"
     },
     "devDependencies": {
-      "aurelia-http-client": "1.0.2"
+      "aurelia-http-client": "npm:aurelia-http-client@^1.0.2"
     }
   }
 }
```

**Comment by phwiget** [comment]
Ok, fixed it. Thanks!
